export default {
  TOKEN_SECRET: 'Bearer',
  API_BREADCRUMBS: '/api/breadcrumbs',
  API_TEMPLATES: '/api/templates',
  API_LEFTNAV: '/api/leftnav',
  API_PRODUCT: '/api/product',
  API_PRODUCT_DETAIL: '/api/productdetails',
  API_PRODUCT_DETAIL_PDP: '/api/productdetails',
  API_PRODUCT_LIST: '/api/productlisting',
  API_SEARCH: '/api/search',
  API_ADD_FAVORITE: '/api/addFavorite',
  API_REMOVE_FAVORITE: '/api/removeFavorite',
  API_FAVORITES: '/api/favorites',
  API_PRODUCT_LIST_METADATA: '/api/productsMetadata',
  API_home: '/api/home',
  API_RECOMMENDATIONS: '/api/recommendations',
  API_BLOOMREACH: '/api/homeRecommendations',
  API_homeRECOMMENDATIONS: '/api/homeRecommendations',
  API_PROMOTION: '/api/product',
  ERROR_PAGE_URL: '/pagenotfound',
  API_MINI_CART: '/api/mini-cart',
  API_RESTRICTED_ITEMS: '/api/restricted-cart-items',
};
